[deps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
Ferrite = "c061ca5d-56c9-439f-9c0e-210fe06d3992"
Thunderbolt = "909927c2-98d5-4a67-bba9-79f03a9ad49b"
