[deps]
CirculatorySystemModels = "4211d73e-f4e8-40c4-b600-92e4b82f0e1a"
Ferrite = "c061ca5d-56c9-439f-9c0e-210fe06d3992"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
ModelingToolkit = "961ee093-0014-501f-94e3-6117800e7a78"
SymbolicIndexingInterface = "2efcf032-c050-4f8e-a9bb-153293bab1f5"
Thunderbolt = "909927c2-98d5-4a67-bba9-79f03a9ad49b"
