name: CI

on:
  pull_request:
  push:
    branches: dev
    tags: '*'

jobs:
  test:
    name: Julia ${{ matrix.julia-version }} - ${{ matrix.os }} - ${{ github.event_name }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.julia-version == 'nightly' }}
    strategy:
      matrix:
        julia-version: ['1.6', '^1.7.0-0', 'nightly']
        os: ['ubuntu-latest']
        include:
          # - os: windows-latest
          #   julia-version: '1'
          - os: macOS-latest
            julia-version: '1'
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      # - uses: julia-actions/julia-buildpkg@v1
      - run: |
          julia --color=yes --project=. -e '
            using Pkg
            Pkg.add(url="https://github.com/Ferrite-FEM/Ferrite.jl.git", rev="master")
            Pkg.instantiate()'
        shell: bash
      - uses: julia-actions/julia-runtest@v1
      # - uses: julia-actions/julia-processcoverage@v1
      # - uses: codecov/codecov-action@v1
      #   with:
      #     file: lcov.info
